[default]
address = "0.0.0.0"
port = 8000
current_tournament_id = 1
code_upload_directory = "./uploads"
code_hash_length = 7

[debug.cookies]
secure = true
same_site = "none"

[release.cookies]
secure = false
same_site = "lax"