name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build api
      working-directory: ./api
      run: cargo build --verbose
    - name: Run api tests
      working-directory: ./api
      run: cargo test --verbose
    - name: Build runner
      working-directory: ./runner
      run: cargo build --verbose
    - name: Run runner tests
      working-directory: ./runner
      run: cargo test --verbose
